### ISSUE TITLE
Budget is not shown

### ISSUE THREAD

**Issue by ivanboytsov** [emansih/FireflyMobile#127]
**Firefly III Server Version:**
5.3.3
**Firefly III Mobile Version:**
3.0.4
**Android Version:**  
9
**Device Information:**  

- BRAND:samsung
- MODEL: galaxy j7
--------------------------------------

## Expected Behavior
I see my budgeted amounts.
## Current Behavior
App shows that my budget is zero despite it isn't.
## Steps to Reproduce
Create budgets for different periods (week, month, year).
See the last plot on Dashboard.

![Screenshot_20200909-190935_Chrome](https://user-images.githubusercontent.com/70232503/92624820-9f6c0f80-f2d0-11ea-83b9-742d1d40f3a3.jpg)
![Screenshot_20200909-190849_Firefly III Mobile](https://user-images.githubusercontent.com/70232503/92624826-a004a600-f2d0-11ea-9dd2-b07bc5266454.jpg)

**Comment by emansih** [comment]
![budget](https://user-images.githubusercontent.com/5896415/92712498-1d95e800-f39d-11ea-81d2-6cd3847b87fc.png)


From your first screenshot, your budgeted is 0. That is why Budget shows 0 in the app.

**Comment by ivanboytsov** [comment]
But it is not 0 in the web app...

**Comment by emansih** [comment]
Hi @ivanboytsov . Just an update to this issue. I have change the logic for the next release. It will show transactions that is associated with your budgets. I will upload an APK for your test it out

**Comment by emansih** [comment]
Hi @ivanboytsov ! Could try this APK, it should fix the budget bug. Thank you! https://drive.google.com/file/d/1YV47voSaoEaq1hpcPyxXEqifuniWGG8z/view?usp=sharing

**Comment by ivanboytsov** [comment]
Yeah, widget looks better now, but crashes on opening.
[Fireflyiii-mobile.txt](https://github.com/emansih/FireflyMobile/files/5487751/Fireflyiii-mobile.txt)

**Comment by ivanboytsov** [comment]
V 3.0.11 still crashes on budget 
[Fireflyiii-mobile-9.txt](https://github.com/emansih/FireflyMobile/files/5577790/Fireflyiii-mobile-9.txt)
